name: py_test_action
description: Test different Python versions using pyenv
inputs:
  python_version:
    description: Python version to use
    required: true
    default: "3.13"
runs:
  using: "composite"
  steps:
  - uses: "gabrielfalcao/pyenv-action@v18"
    name: pyenv install
    with:
      default: "3.8"
      command: "python --version"
  - name: Get latest Python patch version
    shell: bash
    id: py_full_ver
    run: |
      # Split the input version to get the major and minor parts
      py_major_part=$(echo "${{ inputs.python_version }}" | cut -d '.' -f 1)
      py_minor_part=$(echo "${{ inputs.python_version }}" | cut -d '.' -f 2)
      latest=$(pyenv install --list | grep -E "^\s*$py_major_part\.$py_minor_part\.[0-9]+$" | tr -d ' ' | sort -V | tail -1)
      echo "latest_py=$latest" >> $GITHUB_OUTPUT

  - uses: "gabrielfalcao/pyenv-action@v18"
    name: python install
    if: always()
    with:
      default: "${{ steps.py_full_ver.outputs.latest_py }}"
      versions: "${{ steps.py_full_ver.outputs.latest_py }}"
      command: "python --version"
      
  - name: test python version
    shell: bash
    if: always()
    run: |
      eval "$(pyenv init -)"
      pyenv global "${{ steps.py_full_ver.outputs.latest_py }}"
      python --version
      python -c "import sys; print(sys.executable)"
      python -c "import sys; print(sys.version_info)"
