name: py_test_action
description: Test different Python versions using pyenv
inputs:
  python_version:
    description: Python version to use
    required: true
    default: "3.13"
runs:
  using: "composite"
  steps:

  - uses: deadsnakes/action@v3.2.0
    name: Install Python ${{ inputs.python_version }}
    with:
      python-version: ${{ inputs.python_version }}
      
  - name: test python version
    shell: bash
    if: always()
    run: |
      python --version
      python -c "import sys; print(sys.executable)"
      python -c "import sys; print(sys.version_info)"
