name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
        - android_abi: x86_64
          swig_args: -DSWIGWORDSIZE64
          openssl_arch: android-x86_64
        - android_abi: x86
          openssl_arch: android-x86
        - android_abi: arm64-v8a
          openssl_arch: android-arm64
          swig_args: -DSWIGWORDSIZE64
        - android_abi: armeabi-v7a
          openssl_arch: android-arm
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v2
      with:
        path: test
    - name: ls
      run: |
        echo $ANDROID_NDK_LATEST_HOME
        ls $ANDROID_NDK_LATEST_HOME
        ls $ANDROID_NDK_LATEST_HOME/toolchains
        ls $ANDROID_NDK_LATEST_HOME/toolchains/llvm
        ls $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt
        ls $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
    - name: build_openssl
      run: |
        git clone --branch OpenSSL_1_1_1n https://github.com/openssl/openssl.git
        cd openssl
        export PATH=$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH 
        echo PATH=$PATH
        export CC=x86_64-linux-android21-clang
        ./Configure ${{ matrix.config.openssl_arch }} --prefix=$GITHUB_WORKSPACE/openssl_install_${{ matrix.config.android_abi }}
        make -j4
        make install
    - name: List of the GitHub Actions environment variables on Windows
      run: printenv