name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:
    
jobs:
  build-gentoo:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: robotraconteur
        repository: robotraconteur/robotraconteur
    - name: install-pkgs
      run: >-
        yum install -y boost-devel cmake ninja-build 
        gcc gcc-c++ make openssl-devel dbus-devel 
        libusb1-devel bluez-libs-devel gtest-devel 
        python3-devel python3-pip python3-numpy 
        python3-pytest zlib-devel swig
    - name: config
      run: >-
        cmake -GNinja -S robotraconteur -B build -DBUILD_TESTING=ON -DBUILD_GEN=ON 
        -DBUILD_PYTHON3=ON -DCMAKE_BUILD_CONFIG=Release 
        -DPYTHON3_EXECUTABLE=/usr/bin/python3
    - name: build
      run: >-
        cmake --build build --config Release
    - name: test
      run: >-
        ctest --test-dir build -C Release
        -E "robotraconteur_test_discovery_loopback|RobotRaconteurService.DiscoveryLoopback" 
        --output-on-failure 
        


    
    