name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  
  build-win:
    runs-on: windows-2019
    strategy:
      matrix:
        config:
          - arch: x64
            vcpkg_triplet: x64-windows-static-md
            cmake_arch: x64
    steps:
    - uses: actions/checkout@v2
      with:
        path: test
    - name: choco
      run: >
        choco install -y visualstudio2017buildtools
    - name: vsdevcmd
      run: >
        dir "C:\Program Files (x86)\Microsoft Visual Studio\"
    - name: vcvars
      uses: TheMrMilchmann/setup-msvc-dev@v1
      with:
        arch: x64
        vs-path: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017"
    - name: List of the GitHub Actions environment variables on Windows
      run: env