name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:
    
jobs:
  windows_test:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    # - name: pip
    #   run: |
    #     pip install .[test]
    #     pip install git+https://github.com/johnwason/simple-launch-process.git
    - name: test
      run: |
        python simple_launch_process.py