name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:
    
jobs:
  build-pyodide:
    runs-on: ubuntu-22.04
    env:
      EMSDK_NUM_CORES: 3
      EMCC_CORES: 3
      PYODIDE_JOBS: 3
      #CCACHE_DIR: /tmp/dep-ccache
    steps:
    - uses: actions/checkout@v4
      with:
        path: rr_src
        repository: robotraconteur/robotraconteur
    # - name: ccache deps
    #   uses: actions/cache@v3
    #   with:
    #     path: |
    #       /tmp/dep-ccache
    #     key: pyodide-deps-${{ hashFiles('Makefile.envs') }}
    - name: apt
      run: |
        sudo apt update
        sudo apt install -y build-essential libboost-all-dev zlib1g-dev libssl-dev libdbus-1-dev libbluetooth-dev libusb-1.0-0-dev
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - run: |
        pip install "pyodide-build>=0.23.0" "numpy<2.0"
        echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV
    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ env.EMSCRIPTEN_VERSION }}
    - name: build pregenerated_src
      run: |
        cmake -S $GITHUB_WORKSPACE/rr_src -B gen_src -DPACKAGE_SWIG_SOURCE_ALL=ON -DBUILD_PYTHON3=ON -DBUILD_TESTING=OFF
        cmake --build gen_src --config Release --target package_source_swig
        cp -r $GITHUB_WORKSPACE/gen_src/generated_src $GITHUB_WORKSPACE/rr_src/
        sudo cmake --build gen_src --config Release --target install -j4
        sudo python -m pip install $GITHUB_WORKSPACE/gen_src/out/Python3
    - run: pyodide build
      working-directory: rr_src/tools/build_files/pyodide
 
        


    
    