name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  
  build-win:
    runs-on: windows-2016
    strategy:
      matrix:
        config:
          - arch: x64
            vcpkg_triplet: x64-windows-static-md
            cmake_arch: x64
    steps:
    - uses: actions/checkout@v2
      with:
        path: robotraconteur
    - name: semver
      run: >
        robotraconteur/packaging/scripts/actions_semver.py --github-env
    - name: List of the GitHub Actions environment variables on Windows
      run: env