name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:
    
jobs:
  windows_test:
    runs-on: ${{ matrix.windows-versions }}
    strategy:
      fail-fast: false
      matrix:
        windows-versions:
          - windows-2019
          - windows-2022
    steps:
    - uses: actions/checkout@v4
      with:
        path: target_ws/src
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v5
      with:
        pkgs: gtest
        triplet: x64-windows-release
        extra-args: --clean-after-build
        token: ${{ github.token }}
        cache-key: ci-${{ matrix.os }}
        revision: 2023.08.09
    - name: configure-msvc
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: update environment
      shell: bash
      run: |
        echo "PATH=${{ env.PATH }};$GITHUB_WORKSPACE\vcpkg\installed\x64-windows-release\bin" >> "$GITHUB_ENV"
        echo "CMAKE_PREFIX_PATH=$GITHUB_WORKSPACE\vcpkg\installed\x64-windows-release" >> "$GITHUB_ENV"

    - name: Build and Tests
      uses: tesseract-robotics/colcon-action@v1
      with:
        upstream-args: --cmake-args -G "Ninja" -DVCPKG_TARGET_TRIPLET=x64-windows-release -DCMAKE_BUILD_TYPE=Release
        target-path: target_ws/src
        target-args: --cmake-args -G "Ninja" -DVCPKG_TARGET_TRIPLET=x64-windows-release -DCMAKE_BUILD_TYPE=Release -DTESSERACT_ENABLE_TESTING=ON
    
    

    