name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  
  build-ubuntu:
    runs-on: ${{ matrix.config.runs_on }}
    container: ${{ matrix.config.container }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-20.04
          runs_on: ubuntu-latest
          container: ubuntu:20.04
          py_platform: manylinux_2_31_x86_64
          python_version: 3.7
        - os: ubuntu-20.04
          runs_on: ubuntu-latest
          container: ubuntu:20.04
          py_platform: manylinux_2_31_x86_64
          python_version: 3.8
        - os: ubuntu-20.04
          runs_on: ubuntu-latest
          container: ubuntu:20.04
          py_platform: manylinux_2_31_x86_64
          python_version: 3.9
        - os: ubuntu-20.04
          runs_on: ubuntu-latest
          container: ubuntu:20.04
          py_platform: manylinux_2_31_x86_64
          python_version: "3.10"
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: '${{ matrix.config.python_version }}'
    - name: print env
      run: printenv
    - name: print python path
      run: echo "${{ steps.setup-python.outputs.python-path }}"
    - name: ls python bin
      run: ls $Python3_ROOT_DIR/bin
    - name: where python
      run: where python
    - name: python ver
      run: python --version
    