name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  
  build-win:
    runs-on: windows-latest
    strategy:
      matrix:
        config:
          - arch: x64
            vcpkg_triplet: x64-windows-static-md
            cmake_arch: x64
    steps:
    - uses: actions/checkout@v2
      with:
        path: test
    - name: vsdevcmd
      run: >
        dir "C:\Program Files\Microsoft Visual Studio\"
        
    - name: List of the GitHub Actions environment variables on Windows
      run: env